#!/bin/bash
# Creates symlinks from home directory to dotfiles

DOT_DIR=~/dotfiles
LINKS=( "~/.emacs" "~/.vim/vimrc" "~/.vim/gvimrc" "~/.conkyrc" "~/.pentadactylrc" "~/.bashrc" )

move_old () {
    OLD_DIR=$DOT_DIR/.old
    if [ -h "$link" ]; then
        rm "$link"
    elif [ -r "$link" ]; then
        [ ! -e "$OLD_DIR" ] && mkdir -p "$OLD_DIR"
        mv "$link" "$OLD_DIR"
    fi
}

for link in $links; do
    fname=${link##*/}
    [ $fname == "." ] && fname=${fname:0:1}
    if [ -e "$DOT_DIR/$fname" ]; then
        move_old
        ln -s "$DOT_DIR/$fname" "$link"
    else
        echo "no file to link to"
    fi
done
